Go Vet and ineffassign suggestions and consequential code optimizations -Applied go vet suggestions:     ./collection.go:58:16: Errorf format %s reads arg #1, but call has 0 args     ./collection.go:64:17: Errorf format %s reads arg #1, but call has 0 args     ./collection.go:90:15: Errorf format %s reads arg #1, but call has 0 args     ./database.go:305:11: Errorf format %q has arg bucket of wrong type *github.com/boltdb/bolt.Bucket     ./database.go:333:11: Errorf format %q has arg bucket of wrong type *github.com/boltdb/bolt.Bucket     ./helper.go:121:2: unreachable code -Applied ineffassign suggestions:     /home/ace28/Dokumente/gocode/src/Brucheion/database.go:200:4: ineffectual assignment to found     /home/ace28/Dokumente/gocode/src/Brucheion/database.go:225:11: ineffectual assignment to err     /home/ace28/Dokumente/gocode/src/Brucheion/database.go:259:11: ineffectual assignment to err     /home/ace28/Dokumente/gocode/src/Brucheion/database.go:302:2: ineffectual assignment to err     /home/ace28/Dokumente/gocode/src/Brucheion/database.go:330:2: ineffectual assignment to err     /home/ace28/Dokumente/gocode/src/Brucheion/helper.go:294:4: ineffectual assignment to next     /home/ace28/Dokumente/gocode/src/Brucheion/initialization.go:54:3: ineffectual assignment to bucket     /home/ace28/Dokumente/gocode/src/Brucheion/initialization.go:58:3: ineffectual assignment to bucket     /home/ace28/Dokumente/gocode/src/Brucheion/login.go:427:4: ineffectual assignment to ok     /home/ace28/Dokumente/gocode/src/Brucheion/validation.go:167:3: ineffectual assignment to BUPointer -BoltRetrieveFirstKey and BolRetrieve have error handling now (where they are called, error is ignored for now)